[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  CI = "false"
  NODE_VERSION = "18.18.0"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--legacy-peer-deps --force"
  VITE_CJS_IGNORE_WARNING = "true"
  SKIP_GENERATE_TYPES = "true"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"